blank_issues_enabled: false
contact_links:
  - name: Contact Bassam Elshoraa on LinkedIn
    url: https://www.linkedin.com/in/bassam-elshoraa/
    about: Send a suggestion, content update, or other feedback directly.
